### ISSUE TITLE
cannot install v1.0.1 - Error: Command failed: npm run dist:modules

### ISSUE THREAD

**Issue by williamli** [raulanatol/react-inline-loaders#412]
`npm install react-inline-loaders` failed at version 1.0.1

`npm install react-inline-loaders@1.0.0` works fine.

```
npm install --save react-inline-loaders

> react-inline-loaders@1.0.1 postinstall /Users/williamli/projects/bbiHQ/atccessio-app/node_modules/react-inline-loaders
> node --harmony --use_strict lib/post_install.js


> fsevents@1.1.1 install /Users/williamli/projects/bbiHQ/atccessio-app/node_modules/react-inline-loaders/node_modules/fsevents
> node install

node-pre-gyp info it worked if it ends with ok
node-pre-gyp verb cli [ '/usr/local/bin/node',
node-pre-gyp verb cli   '/Users/williamli/projects/bbiHQ/atccessio-app/node_modules/react-inline-loaders/node_modules/fsevents/node_modules/.bin/node-pre-gyp',
node-pre-gyp verb cli   'install',
node-pre-gyp verb cli   '--fallback-to-build' ]
node-pre-gyp info using node-pre-gyp@0.6.33
node-pre-gyp info using node@6.10.0 | darwin | x64
node-pre-gyp verb command install []
node-pre-gyp info validate Running test command: '/usr/local/bin/node --eval 'require(\'/Users/williamli/projects/bbiHQ/atccessio-app/node_modules/react-inline-loaders/node_modules/fsevents/lib/binding/Release/node-v48-darwin-x64/fse.node\')''
[fsevents] Success: "/Users/williamli/projects/bbiHQ/atccessio-app/node_modules/react-inline-loaders/node_modules/fsevents/lib/binding/Release/node-v48-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile
node-pre-gyp info ok 
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN react-inline-loaders@1.0.1 requires a peer of react@^15.5.4 but none was installed.
npm WARN react-inline-loaders@1.0.1 requires a peer of react-css-modules@^4.3.0 but none was installed.
npm WARN react-inline-loaders@1.0.1 requires a peer of react-dom@^15.5.4 but none was installed.

+ babel-preset-react@6.24.1
+ babel-cli@6.24.1
+ babel-preset-es2015@6.24.1
added 290 packages in 32.369s
npm ERR! missing script: dist:modules

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/williamli/.npm/_logs/2017-06-12T09_18_59_006Z-debug.log
child_process.js:526
    throw err;
    ^

Error: Command failed: npm run dist:modules
    at checkExecSyncError (child_process.js:483:13)
    at execSync (child_process.js:523:13)
    at exec (/Users/williamli/projects/bbiHQ/atccessio-app/node_modules/react-inline-loaders/lib/post_install.js:11:3)
    at stat (/Users/williamli/projects/bbiHQ/atccessio-app/node_modules/react-inline-loaders/lib/post_install.js:24:5)
npm WARN react-inline-loaders@1.0.1 requires a peer of react-css-modules@^4.3.0 but none was installed.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-inline-loaders@1.0.1 postinstall: `node --harmony --use_strict lib/post_install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-inline-loaders@1.0.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/williamli/.npm/_logs/2017-06-12T09_19_10_181Z-debug.log


```

**Comment by raulanatol** [comment]
Hi @williamli!
Thx for your feedback.
I've published a new version v1.0.2 removing the dist:modules script

**Comment by williamli** [comment]
@raulanatol npm still points to 1.0.1 as latest

**Comment by raulanatol** [comment]
Sorry @williamli test again, please.

**Comment by williamli** [comment]
a few problems:

1. dist folder is missing, it used to contain a css file, now the css file is gone.
2. when `import {DotLineLoader} from 'react-inline-loaders';` I get error `Cannot find module 'react-inline-loaders`.

upon looking into the react-inline-loaders inside node_modules folder, it turns out it doesn't really contain any code...?
<img width="203" alt="screen shot 2017-06-16 at 01 52 38" src="https://user-images.githubusercontent.com/179761/27194808-a10a4a2a-5236-11e7-898b-746641e1eae4.png">

**Comment by raulanatol** [comment]
Sorry @williamli.
The Webpack migration was a mess.
I've uploaded a new version 1.0.3.
Thx!!

**Comment by williamli** [comment]
seems to be working fine now.

btw @raulanatol , it did complain about `react-css-modules` but I cannot find `react-css-modules` in npm.

```
warning "react-inline-loaders@1.0.3" has unmet peer dependency "react-css-modules@^4.3.0".
```

**Comment by raulanatol** [comment]
@williamli this is the module: https://github.com/gajus/react-css-modules
```
yarn add react-css-modules
```

**Comment by williamli** [comment]
@raulanatol thanks. i must have typed the wrong name last time when I tried to add it. works fine now.
